version: "3"
services:

  jenkins:
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    container_name: jenkins
    
    volumes: 
      - ./jenkins:/var/jenkins_home:rw
 
  artifactory:
    image: mzain/artifactory-oss:5.4.4
    ports:
      - "9090:8081"
    container_name: artifactory
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory:rw
